=== fyyyfi/OOP_lab2/src/main/resources/old_cards.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="ThemaType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Cityscape"/>
            <xs:enumeration value="Nature"/>
            <xs:enumeration value="People"/>
            <xs:enumeration value="Religion"/>
            <xs:enumeration value="Sport"/>
            <xs:enumeration value="Architecture"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="CardTypeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Greeting"/>
            <xs:enumeration value="Advertising"/>
            <xs:enumeration value="Regular"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ValuableType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Historical"/>
            <xs:enumeration value="Collectible"/>
            <xs:enumeration value="Thematic"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="OldCardType">
        <xs:sequence>
            <xs:element name="Thema" type="ThemaType"/>
            <xs:element name="Type" type="CardTypeType"/>
            <xs:element name="Country" type="xs:string"/>
            <xs:element name="Year" type="xs:gYear"/>
            <xs:element name="Author" type="xs:string" minOccurs="0"/> <xs:element name="Valuable" type="ValuableType"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/> <xs:attribute name="sent" type="xs:boolean" use="required"/> </xs:complexType>

    <xs:element name="OldCards">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="OldCard" type="OldCardType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== fyyyfi/OOP_lab2/src/main/resources/old_cards.xml
<?xml version="1.0" encoding="UTF-8"?>
<OldCards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="old_cards.xsd">

    <OldCard id="card001" sent="true">
        <Thema>Cityscape</Thema>
        <Type>Regular</Type>
        <Country>Ukraine</Country>
        <Year>1985</Year>
        <Author>N. Kovalenko</Author>
        <Valuable>Thematic</Valuable>
    </OldCard>

    <OldCard id="card002" sent="false">
        <Thema>Nature</Thema>
        <Type>Greeting</Type>
        <Country>Poland</Country>
        <Year>1992</Year>
        <Valuable>Collectible</Valuable>
    </OldCard>

    <OldCard id="card003" sent="true">
        <Thema>Architecture</Thema>
        <Type>Advertising</Type>
        <Country>Germany</Country>
        <Year>2001</Year>
        <Author>H. Schmidt</Author>
        <Valuable>Historical</Valuable>
    </OldCard>

    <OldCard id="card004" sent="false">
        <Thema>People</Thema>
        <Type>Regular</Type>
        <Country>Ukraine</Country>
        <Year>1976</Year>
        <Valuable>Collectible</Valuable>
    </OldCard>
</OldCards>
